### ZSH settings ###
ZSH_THEME="norm"
COMPLETION_WAITING_DOTS="true"


### Completion ###
fpath=(~/.zsh/completion $fpath) # add custom completion to fpath
setopt COMPLETE_IN_WORD
autoload -U compinit
compinit
zstyle ':completion::complete:*' use-cache 1
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' # case insensitive completion
zstyle ':completion:*:default' menu 'select=0'      # menu-style

### Colors ###
export CLICOLOR=1
autoload colors
colors
[[ -d ~/junk_drawer ]] && source ~/junk_drawer/scripts/color_functions.sh # Color helper functions

### History ###
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000
setopt EXTENDED_HISTORY     # add timestamps to history
setopt APPEND_HISTORY       # adds history
setopt INC_APPEND_HISTORY   # adds history incrementally
setopt SHARE_HISTORY        # share across sessions
setopt HIST_IGNORE_ALL_DUPS # don't record dupes in history
setopt HIST_IGNORE_DUPS
setopt HIST_REDUCE_BLANKS

### more ZSH settings ###
unsetopt correct_all
bindkey -e                                       # use emacs key bindings
bindkey '^r' history-incremental-search-backward # make Control-r work
bindkey '^[[Z' reverse-menu-complete             # shift-tab to cycle backwards
bindkey "^[[3~" delete-char                      # make delete key work
bindkey "^[3;5~" delete-char                     # make delete key work
autoload -U select-word-style
select-word-style bash

setopt LOCAL_OPTIONS # allow functions to have local options
setopt LOCAL_TRAPS   # allow functions to have local traps
setopt PROMPT_SUBST
setopt AUTO_CD
stty -ixon -ixoff    # disable scroll lock
export EDITOR=vim
set -o emacs

source $HOME/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $HOME/.zsh/scripts/aliases.zsh
source $HOME/.zsh/scripts/prompt.zsh


### OS-specific settings ###
if on_linux; then
    prompt_branch_color='blue'
    prompt_path_color='magenta'
    alias ls='ls --color'
else
    prompt_branch_color='cyan'
    prompt_path_color='red'
    alias ls='ls -G'

    source $(brew --prefix)/etc/profile.d/z.sh
    _Z_EXCLUDE_DIRS=("$HOME/.gem" "$HOME/.rubies" "$HOME/Library" "$HOME/work/enova/8b/gems/portfolio_client" "$HOME/work/enova/8b/gems/identity_client")
    # source ~/.zsh/export_homebrew_github_api_token.sh
fi


### Helpers ###
function show-path()        { echo $PATH | tr ':' '\n' }

# add WTFPL license
function wtfpl() {
    if [ -f COPYING ]; then
        echo 'COPYING file already exists'
    else
        cat > COPYING <<- EOM
        DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
                    Version 2, December 2004

 Copyright (C) 2015 Ben Trevor <benjamin.trevor@gmail.com>

 Everyone is permitted to copy and distribute verbatim or modified
 copies of this license document, and changing it is allowed as long
 as the name is changed.

            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION

  0. You just DO WHAT THE FUCK YOU WANT TO.
EOM
    fi
}

function rename_box() {
    OLD_BOX_NAME=$1
    PROVIDER=$2
    NEW_BOX_NAME=$3

    echo "repackaging $OLD_BOX_NAME..."
    vagrant box repackage $OLD_BOX_NAME $PROVIDER
    echo "adding $NEW_BOX_NAME..."
    vagrant box add $NEW_BOX_NAME package.box
    rm package.box
    vagrant box remove $OLD_BOX_NAME
    echo 'Success!'
}

### set up session ###
function global_bins()  { echo '/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin' }
function gem_bins()     { echo "$GEM_HOME/bin" }
function cabal_bins()     { echo "$HOME/.cabal/bin" }
function go_bins()      { echo "$GOPATH/bin" }

export GOPATH=$HOME/go
export PATH=$(gem_bins):$(global_bins):$(cabal_bins):$(go_bins)

chpwd
